"""
Seed plant_profiles into any database (SQLite or PostgreSQL).
Usage:
  Local SQLite:  python seed_db.py
  Remote PG:     set DATABASE_URL=postgresql+asyncpg://... && python seed_db.py
"""

import asyncio
import os
from datetime import datetime, timezone

from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

DB_URL = os.environ.get("DATABASE_URL", "sqlite:///./irrigation.db")

# Normalize for sync engine
if DB_URL.startswith("postgresql+asyncpg"):
    DB_URL = DB_URL.replace("postgresql+asyncpg", "postgresql", 1)

engine = create_engine(DB_URL, echo=False)
Session = sessionmaker(bind=engine)

PLANTS = [
    # (name, category, moisture_min, moisture_max, ideal_moisture,
    #  temp_min, temp_max, humidity_min, humidity_max, decay/hr, description)
    (
        "Rice",
        "crop",
        60,
        95,
        75,
        20,
        38,
        60,
        95,
        3.0,
        "Staple cereal crop requiring flooded conditions during growth.",
    ),
    (
        "Wheat",
        "crop",
        35,
        65,
        50,
        10,
        30,
        30,
        70,
        2.0,
        "Cool-season cereal grain grown across northern India.",
    ),
    (
        "Maize",
        "crop",
        40,
        75,
        55,
        18,
        35,
        40,
        80,
        2.5,
        "Versatile cereal used for food, feed, and industrial products.",
    ),
    (
        "Chickpea",
        "legume",
        30,
        60,
        45,
        15,
        35,
        30,
        70,
        1.8,
        "Leading pulse crop in India, drought-tolerant.",
    ),
    (
        "Pigeon Pea / Arhar",
        "legume",
        30,
        65,
        45,
        18,
        38,
        35,
        75,
        1.8,
        "Important dal crop, deep-rooted and drought-resistant.",
    ),
    (
        "Moong",
        "legume",
        35,
        70,
        50,
        20,
        38,
        40,
        80,
        2.0,
        "Fast-growing summer pulse, green gram.",
    ),
    (
        "Urad Dal",
        "legume",
        35,
        70,
        50,
        20,
        38,
        40,
        80,
        2.0,
        "Black gram, essential for Indian dal and batter.",
    ),
    (
        "Tomato",
        "vegetable",
        50,
        85,
        65,
        18,
        38,
        45,
        85,
        3.0,
        "High-value vegetable requiring consistent moisture.",
    ),
    (
        "Potato",
        "vegetable",
        45,
        75,
        60,
        15,
        28,
        40,
        80,
        2.5,
        "Cool-season tuber crop, India's top vegetable.",
    ),
    (
        "Brinjal",
        "vegetable",
        50,
        80,
        65,
        20,
        38,
        50,
        85,
        2.8,
        "Eggplant, widely grown across Indian states.",
    ),
    (
        "Chilli Pepper",
        "spice",
        40,
        75,
        55,
        20,
        38,
        40,
        80,
        2.5,
        "India's top spice export, requires warm conditions.",
    ),
    (
        "Cucumber",
        "vegetable",
        55,
        90,
        70,
        20,
        40,
        50,
        90,
        3.5,
        "Summer vine crop needing high moisture.",
    ),
    (
        "Bitter Gourd",
        "vegetable",
        55,
        85,
        70,
        22,
        38,
        55,
        90,
        3.0,
        "Medicinal vine vegetable, popular in Indian cuisine.",
    ),
    (
        "Bottle Gourd",
        "vegetable",
        55,
        90,
        70,
        22,
        38,
        55,
        90,
        3.5,
        "Summer gourd requiring consistent watering.",
    ),
    (
        "Okra / Bhindi",
        "crop",
        45,
        80,
        60,
        20,
        40,
        40,
        85,
        2.5,
        "Heat-loving vegetable, staple in Indian cooking.",
    ),
    (
        "Cotton",
        "crop",
        45,
        80,
        60,
        20,
        40,
        40,
        85,
        2.5,
        "Major fiber crop, requires warm growing season.",
    ),
    (
        "Onion",
        "vegetable",
        35,
        70,
        50,
        10,
        35,
        30,
        75,
        1.8,
        "Essential kitchen crop, moderate water needs.",
    ),
    (
        "Garlic",
        "vegetable",
        35,
        70,
        50,
        10,
        35,
        30,
        75,
        1.8,
        "Cool-season bulb crop with moderate moisture needs.",
    ),
    (
        "Ginger",
        "spice",
        60,
        90,
        75,
        20,
        35,
        60,
        95,
        2.8,
        "Rhizome spice requiring warm, humid conditions.",
    ),
    (
        "Turmeric",
        "spice",
        60,
        90,
        75,
        20,
        35,
        60,
        95,
        2.8,
        "Golden spice, native to India, needs high moisture.",
    ),
    (
        "Coriander",
        "herb",
        40,
        75,
        55,
        10,
        35,
        35,
        75,
        2.0,
        "Most used herb in Indian cuisine, cool-season.",
    ),
    (
        "Cumin",
        "spice",
        25,
        55,
        40,
        15,
        35,
        25,
        65,
        1.5,
        "Drought-tolerant spice, grown in Rajasthan and Gujarat.",
    ),
    (
        "Mustard",
        "oilseed",
        40,
        70,
        55,
        10,
        30,
        40,
        75,
        2.2,
        "Rabi oilseed crop, source of mustard oil.",
    ),
    (
        "Sugarcane",
        "crop",
        65,
        95,
        80,
        20,
        38,
        60,
        95,
        4.0,
        "Water-intensive cash crop, India's top sugar source.",
    ),
    (
        "Mango",
        "tree",
        35,
        70,
        50,
        20,
        45,
        35,
        80,
        1.5,
        "India's national fruit, drought-tolerant once established.",
    ),
    (
        "Banana",
        "herb",
        65,
        95,
        80,
        20,
        38,
        60,
        95,
        3.5,
        "India's top fruit crop, requires high moisture year-round.",
    ),
    (
        "Coconut",
        "palm",
        60,
        95,
        75,
        22,
        38,
        60,
        95,
        3.0,
        "Tropical palm requiring high humidity and rainfall.",
    ),
    (
        "Guava",
        "tree",
        40,
        75,
        55,
        15,
        42,
        40,
        85,
        1.8,
        "Hardy tropical fruit tree, widely grown.",
    ),
    (
        "Lemon",
        "tree",
        50,
        80,
        65,
        15,
        38,
        45,
        85,
        2.0,
        "Citrus tree requiring consistent moisture.",
    ),
    (
        "Neem",
        "tree",
        25,
        60,
        40,
        15,
        48,
        25,
        75,
        1.2,
        "Drought-tolerant medicinal tree, India's village pharmacy.",
    ),
    (
        "Tulsi / Holy Basil",
        "herb",
        45,
        80,
        60,
        15,
        38,
        40,
        85,
        2.5,
        "Sacred medicinal herb, grown in Indian households.",
    ),
    (
        "Moringa / Drumstick",
        "tree",
        25,
        60,
        40,
        20,
        45,
        25,
        70,
        1.5,
        "Highly nutritious, drought-tolerant superfood tree.",
    ),
    (
        "Tea",
        "shrub",
        60,
        95,
        75,
        12,
        30,
        60,
        95,
        2.5,
        "Assam and Darjeeling tea, requires high rainfall.",
    ),
    (
        "Coffee",
        "shrub",
        55,
        85,
        70,
        15,
        28,
        55,
        90,
        2.2,
        "Grown in Karnataka, Kerala, and Tamil Nadu hills.",
    ),
    (
        "Black Pepper",
        "spice",
        65,
        95,
        80,
        22,
        35,
        65,
        95,
        2.5,
        "King of spices, native to Western Ghats.",
    ),
    (
        "Cardamom",
        "spice",
        65,
        95,
        80,
        18,
        35,
        65,
        95,
        2.5,
        "Queen of spices, grown in Kerala and Tamil Nadu.",
    ),
    (
        "Sandalwood",
        "tree",
        30,
        60,
        45,
        15,
        38,
        30,
        75,
        1.2,
        "Precious aromatic tree, semi-parasitic.",
    ),
    (
        "Ashwagandha",
        "herb",
        30,
        60,
        45,
        15,
        38,
        30,
        70,
        1.8,
        "Adaptogenic medicinal herb, drought-tolerant.",
    ),
    (
        "Amla / Indian Gooseberry",
        "tree",
        35,
        65,
        50,
        15,
        42,
        35,
        80,
        1.5,
        "Vitamin C-rich fruit tree, highly medicinal.",
    ),
    (
        "Papaya",
        "tree",
        55,
        85,
        70,
        20,
        38,
        55,
        90,
        3.0,
        "Fast-growing tropical fruit, needs consistent moisture.",
    ),
    (
        "Lychee",
        "tree",
        50,
        80,
        65,
        18,
        38,
        50,
        85,
        1.8,
        "Premium tropical fruit, grown in Bihar and Jharkhand.",
    ),
    (
        "Jasmine",
        "flower",
        45,
        80,
        60,
        18,
        38,
        45,
        85,
        2.5,
        "Fragrant ornamental, widely used in garlands.",
    ),
    (
        "Marigold",
        "flower",
        40,
        75,
        55,
        15,
        38,
        40,
        80,
        2.2,
        "Most popular Indian ornamental flower.",
    ),
    (
        "Lotus",
        "flower",
        70,
        100,
        85,
        20,
        38,
        60,
        95,
        1.5,
        "Aquatic sacred flower, grows in ponds.",
    ),
    (
        "Hibiscus",
        "flower",
        45,
        80,
        60,
        18,
        38,
        45,
        85,
        2.5,
        "Ornamental and medicinal flower.",
    ),
    (
        "Bamboo",
        "grass",
        50,
        85,
        65,
        18,
        40,
        50,
        90,
        2.5,
        "Fast-growing grass used for construction and crafts.",
    ),
    (
        "Teak",
        "tree",
        40,
        75,
        55,
        18,
        42,
        40,
        80,
        1.5,
        "Premium timber tree, valuable hardwood.",
    ),
    (
        "Jamun",
        "tree",
        40,
        75,
        55,
        15,
        42,
        40,
        85,
        1.8,
        "Black plum, medicinal fruit tree.",
    ),
    (
        "Cashew",
        "tree",
        35,
        65,
        50,
        20,
        40,
        35,
        75,
        1.5,
        "Nut tree grown in coastal regions.",
    ),
    (
        "Sesame / Til",
        "oilseed",
        30,
        60,
        45,
        20,
        38,
        30,
        70,
        1.8,
        "Ancient oilseed, drought-tolerant.",
    ),
    (
        "Groundnut",
        "legume",
        35,
        65,
        50,
        20,
        35,
        35,
        75,
        2.0,
        "Major oilseed and snack crop.",
    ),
    (
        "Soybean",
        "legume",
        40,
        75,
        55,
        20,
        35,
        40,
        80,
        2.2,
        "Protein-rich legume, MP's top crop.",
    ),
    (
        "Sunflower",
        "flower",
        35,
        65,
        50,
        18,
        38,
        35,
        75,
        2.0,
        "Oilseed and ornamental, drought-tolerant.",
    ),
    (
        "Mint / Pudina",
        "herb",
        50,
        85,
        65,
        15,
        35,
        50,
        90,
        2.8,
        "Aromatic herb, spreads rapidly in moist soil.",
    ),
    (
        "Basil",
        "herb",
        45,
        80,
        60,
        18,
        38,
        45,
        85,
        2.5,
        "Culinary and medicinal aromatic herb.",
    ),
    (
        "Aloe Vera",
        "succulent",
        10,
        40,
        25,
        15,
        40,
        20,
        60,
        1.0,
        "Medicinal succulent, very drought-tolerant.",
    ),
    (
        "Rose",
        "flower",
        40,
        75,
        55,
        10,
        35,
        40,
        80,
        2.2,
        "Most popular ornamental flower worldwide.",
    ),
    (
        "Lavender",
        "herb",
        25,
        55,
        40,
        10,
        35,
        25,
        65,
        1.5,
        "Aromatic herb, prefers well-drained soil.",
    ),
]


def seed():
    print(f"Seeding database: {DB_URL}")
    with engine.connect() as conn:
        # Ensure table exists
        conn.execute(
            text("""
            CREATE TABLE IF NOT EXISTS plant_profiles (
                id SERIAL PRIMARY KEY,
                name VARCHAR(100) NOT NULL UNIQUE,
                category VARCHAR(50) NOT NULL,
                moisture_min FLOAT NOT NULL,
                moisture_max FLOAT NOT NULL,
                ideal_moisture FLOAT NOT NULL,
                temp_min FLOAT NOT NULL,
                temp_max FLOAT NOT NULL,
                humidity_min FLOAT NOT NULL,
                humidity_max FLOAT NOT NULL,
                avg_moisture_decay_per_hour FLOAT NOT NULL,
                description TEXT,
                created_at TIMESTAMP NOT NULL DEFAULT NOW()
            )
        """)
        )
        conn.commit()

        inserted = 0
        skipped = 0
        for p in PLANTS:
            try:
                conn.execute(
                    text("""
                    INSERT INTO plant_profiles
                    (name, category, moisture_min, moisture_max, ideal_moisture,
                     temp_min, temp_max, humidity_min, humidity_max,
                     avg_moisture_decay_per_hour, description, created_at)
                    VALUES (:name, :category, :moisture_min, :moisture_max, :ideal_moisture,
                            :temp_min, :temp_max, :humidity_min, :humidity_max,
                            :decay, :description, :created_at)
                    ON CONFLICT (name) DO NOTHING
                """),
                    {
                        "name": p[0],
                        "category": p[1],
                        "moisture_min": p[2],
                        "moisture_max": p[3],
                        "ideal_moisture": p[4],
                        "temp_min": p[5],
                        "temp_max": p[6],
                        "humidity_min": p[7],
                        "humidity_max": p[8],
                        "decay": p[9],
                        "description": p[10],
                        "created_at": datetime.now(timezone.utc),
                    },
                )
                if conn.execute(text("SELECT changes()")).scalar() > 0:
                    inserted += 1
                else:
                    skipped += 1
            except Exception as e:
                skipped += 1
        conn.commit()

    print(f"Done! Inserted: {inserted}, Skipped (duplicate): {skipped}")


if __name__ == "__main__":
    seed()
